"""
Regenerate brand_assets.py from Logo.png.

Usage:
  python tools/refresh_brand_assets.py

Then rebuild Node / Control Panel so the new bytes ship inside the exe.
"""
from __future__ import annotations

import base64
import datetime
import hashlib
import io
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC_PNG = ROOT / "Logo.png"
OUT_PY = ROOT / "brand_assets.py"
OUT_ICO = ROOT / "Logo.ico"


def _wrap_b64(data: bytes, width: int = 76) -> str:
    s = base64.b64encode(data).decode("ascii")
    return "\n".join(s[i : i + width] for i in range(0, len(s), width))


def _chunk_b64(data: bytes, width: int = 76) -> str:
    """Emit adjacent string literals that Python concatenates at compile time."""
    s = base64.b64encode(data).decode("ascii")
    parts = [s[i : i + width] for i in range(0, len(s), width)]
    return "\n".join(f'    "{part}"' for part in parts)


def _is_light(r: int, g: int, b: int) -> bool:
    return r >= 215 and g >= 215 and b >= 215 and abs(r - g) <= 25 and abs(g - b) <= 25


def prepare_logo_alpha(im: Image.Image) -> Image.Image:
    """
    Export cleanup for circular brand marks:
    - Outside the ring: transparent (keeps jet nose that protrudes)
    - Inside the ring: leave artwork as-is (including white sky)
    """
    import math

    im = im.convert("RGBA")
    w, h = im.size
    pix = im.load()
    cx, cy = w / 2, h / 2

    radii = []
    for angle in range(0, 360, 2):
        rad = math.radians(angle)
        for d in range(min(w, h) // 2, max(40, min(w, h) // 8), -1):
            x = int(cx + d * math.cos(rad))
            y = int(cy + d * math.sin(rad))
            if not (0 <= x < w and 0 <= y < h):
                continue
            r, g, b, a = pix[x, y]
            if not _is_light(r, g, b) and (r + g + b) > 30:
                radii.append(d)
                break
    if not radii:
        return im
    outer_r = sorted(radii)[len(radii) // 2]

    for y in range(h):
        for x in range(w):
            r, g, b, a = pix[x, y]
            dist = math.hypot(x - cx, y - cy)
            if dist <= outer_r + 2:
                continue
            # Outside ring: clear light export background only
            if _is_light(r, g, b) or (r > 200 and g > 200 and b > 200):
                pix[x, y] = (0, 0, 0, 0)
            elif dist > outer_r + 50 and r > 180 and g > 180 and b > 180:
                pix[x, y] = (0, 0, 0, 0)
    return im


def main() -> int:
    if not SRC_PNG.exists():
        print(f"ERROR: missing {SRC_PNG}", file=sys.stderr)
        return 1

    im = prepare_logo_alpha(Image.open(SRC_PNG))
    im.save(SRC_PNG)  # persist cleaned master
    ui = im.resize((256, 256), Image.Resampling.LANCZOS)

    png_buf = io.BytesIO()
    ui.save(png_buf, format="PNG", optimize=True)
    png_bytes = png_buf.getvalue()

    ico_buf = io.BytesIO()
    ui.save(
        ico_buf,
        format="ICO",
        sizes=[(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)],
    )
    ico_bytes = ico_buf.getvalue()

    # Keep on-disk ICO for PyInstaller icon= at build time
    im.save(
        OUT_ICO,
        format="ICO",
        sizes=[(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)],
    )

    md5 = hashlib.md5(png_bytes).hexdigest()
    version = datetime.date.today().isoformat().replace("-", ".")

    OUT_PY.write_text(
        f'''"""
Embedded DCS Norway brand assets.

AUTO-GENERATED by tools/refresh_brand_assets.py — do not edit by hand.
To change the logo:
  1. Replace Logo.png in the repo root
  2. Run:  python tools/refresh_brand_assets.py
  3. Rebuild Node / Control Panel
"""
from __future__ import annotations

import base64
import io
import os

BRAND_ASSET_VERSION = "{version}"
BRAND_PNG_MD5 = "{md5}"

_PNG_B64 = (
{_chunk_b64(png_bytes)}
)

_ICO_B64 = (
{_chunk_b64(ico_bytes)}
)


def logo_png_bytes() -> bytes:
    return base64.b64decode(_PNG_B64)


def logo_ico_bytes() -> bytes:
    return base64.b64decode(_ICO_B64)


def logo_pil_image():
    """RGBA PIL Image of the brand logo (always from embedded bytes)."""
    from PIL import Image

    return Image.open(io.BytesIO(logo_png_bytes())).convert("RGBA")


def materialize_icon_file(directory: str, filename: str = "dcs_norway_brand.ico") -> str:
    """Write embedded ICO for Tk iconbitmap / Qt window icon."""
    os.makedirs(directory, exist_ok=True)
    path = os.path.join(directory, filename)
    data = logo_ico_bytes()
    if os.path.exists(path) and os.path.getsize(path) == len(data):
        with open(path, "rb") as f:
            if f.read() == data:
                return path
    with open(path, "wb") as f:
        f.write(data)
    return path
''',
        encoding="utf-8",
    )

    print(f"Wrote {OUT_PY.name} (png={len(png_bytes)}B ico={len(ico_bytes)}B md5={md5})")
    print(f"Wrote {OUT_ICO.name}")
    print(f"BRAND_ASSET_VERSION={version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
